### ISSUE TITLE
Cake command always returns with error

### ISSUE THREAD

**Issue by Cheesebaron** [phillipsj/Cake.Squirrel#7]
For some reason when using Squirrel in Cake I always get an error after 1.5 minutes (very consistently). However, it seems like the Setup.exe is created correctly.

```
Executing task: create-squirrel-installer
Executing: "C:/vcs/git/survey-app3/Script/tools/squirrel.windows/tools/Squirrel.exe" --releasify C:/vcs/git/survey-app3/artifacts/SurveyOffice.0.1.0.nupkg
An error occurred when executing task 'create-squirrel-installer'.
Squirrel.exe threw an error, Setup.exe might still be ok
Cake.Core.CakeException: Squirrel: Process returned an error (exit code -1).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Squirrel.SquirrelRunner.Run(FilePath nugetPackage, SquirrelSettings settings, ProcessSettings processSettings)
   at Submission#0.<.ctor>b__18()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass5_0.<Does>b__0(ICakeContext context)
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
```

Currently I've just told my cake script to ignore that error.

It should be noted, when I run the command directly from CMD or PowerShell it returns immediately and builds the Setup file in the background.

**Comment by Cheesebaron** [comment]
Oh yeah, the line "Squirrel.exe threw an error..." is something I output myself, just to not confuse you.

Ultimately, I don't know if this is actually an error with Cake.Squirrel but rather Squirrel.exe that returns prematurely. Is there a way to observe whether the process actually exits or get some status of what Squirrel.exe is doing? It seems so silent.

**Comment by Cheesebaron** [comment]
OK. Non issue. I was using special characters in the NuGet Description, which WiX does not seem to like...

After changing those, it seems to work just fine.
